# -*- coding: utf-8 -*-
"""Promedios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17qSorJDVU7cTXYq7hlDkt0_fcXjDULVT
"""

import os
import pandas as pd
from pathlib import Path

dir='/content/drive/Shareddrives/Proyecto_drones_Unal_Oopart/Yolo_v6/Inference_on_NVIDIA_Jetson_Nano/Mix_Source_Labels/labels'+'/'
rootdir=os.listdir(dir)
rootdir.sort(key=lambda s: int(s.split('.txt')[0][-1]))

newdf=pd.DataFrame()

filas={0:'awning-tricycle',
       1:'biclycle',
       2:'bus',
       3:'car',
       4:'motor',
       5:'pedestrian',
       6:'people',
       7:'tricycle',
       8:'truck',
       9:'van'}

for i in range(len(rootdir)):
  df = pd.read_csv(dir+rootdir[i], sep=" ",header=None)
  r=df[0].value_counts()
  newdf=pd.concat([newdf,r],axis=1, ignore_index=True)
newdf=newdf.sort_index()
newdf=newdf.rename(index=filas)

newdf

newdf1=newdf.mean(axis=1)

import numpy as np

newdf=pd.concat([newdf,newdf1.apply(np.ceil)],axis=1,ignore_index=True)
newdf

import matplotlib.pyplot as plt

plt.barh(newdf.index,newdf.loc[:,newdf.columns.values[-1]])

newdf2=newdf.sum(axis=1)-newdf[newdf.columns.values[-1]]
newdf2

sumas=pd.DataFrame(newdf2)
sumas

h=sumas.index.to_numpy().tolist()
h

f=sumas[0].to_numpy().tolist()
f

fig =plt.figure(figsize = (4,4))
ax11 = fig.add_subplot(111)
w,l,p = ax11.pie(f, autopct='%1.1f%%', pctdistance=1, radius = 0.5)

pctdists = [.1,.25,.4,.55,.7,.85,1,1.15,1.3]

for t,d in zip(p, pctdists):
    xi,yi = t.get_position()
    ri = np.sqrt(xi**2+yi**2)
    phi = np.arctan2(yi,xi)
    x = d*ri*np.cos(phi)
    y = d*ri*np.sin(phi)
    t.set_position((x,y))
ax11.legend(labels=h, loc="upper center", ncol=2)
plt.axis('equal')
plt.savefig("Ejemplo1.jpg")
plt.show()